### ISSUE TITLE
Receive notifications for messages and conversations

### ISSUE THREAD

**Issue by superseby2** [humhub-contrib/fcm-push#5]
Hi! 

Thanks for fcm-push ! It's working out of the box. 

Are you planning to support Notifications for messages and conversations? 

Currently those 2 events are greyed-out in the Settings. 

Thx!

**Comment by buddh4** [comment]
This is rather an issue with the message module: https://github.com/humhub/humhub-modules-mail/issues/170

**Comment by luke-** [comment]
Yes

**Comment by donni106** [comment]
Can you point me to the codes here, that we can dig deeper on the implementation? Any further information on how this was integrated and connected to the messenger module would also be very helpful.
